---
- name: Check firewalld package is installed (on RHEL).
  shell: yum list installed firewalld
  register: firewalld_installed
  ignore_errors: true
  when: ansible_os_family == "Fedora" and firewall_disable_firewalld
  tags:
  - firewalld

- name: Disable the firewalld service (on RHEL, if configured).
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_os_family == "Fedora" and firewall_disable_firewalld and firewalld_installed.rc == 0
  tags:
  - firewalld
