---

- debug: var=ansible_distribution
- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'

- name: Include version-specific variables for Fedora
  include_vars: "Fedora-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "Fedora" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Include version-specific variables for Alpine
  include_vars: "Alpine.yml"
  when: ansible_os_family == "Alpine"

- debug: var=ansible_os_family
- debug: var=ipv6_config
- block:
    - include: ipv6-harden.yml
      when: ipv6_config is defined and ipv6_config == 'harden'
    - include: ipv6-disable.yml
      when: ipv6_config is not defined or ipv6_config == 'disable'
  when: ansible_system == 'Linux'

