---

ipv6_harden_settings:
    - { n: 'net.ipv6.conf.all.forwarding', v: 0 }
    - { n: 'net.ipv6.conf.all.accept_source_route', v: 0 }
    - { n: 'net.ipv6.conf.default.accept_source_route', v: 0 }

