---
- name: /etc/modules-load.d/nf.conf
  copy: content=nf_conntrack
        dest=/etc/modules-load.d/nf.conf
        owner=root
        group=root
        mode=0644
        backup=yes

- name: Create /etc/systemd/system/docker.service.d/
  file: path="/etc/systemd/system/docker.service.d/"
        state=directory
        mode=0755
        recurse=yes
        owner="root"
        group="root"

# - name: Create /etc/systemd/system/docker.service.d/increase-ulimit.conf
#   file: src="{{ role_path }}/files/etc/systemd/system/docker.service.d/increase-ulimit.conf"
#         path="/etc/systemd/system/docker.service.d/increase-ulimit.conf"
#         mode=0644
#         owner="root"
#         group="root"

# Set vm.swappiness to 5 in /etc/sysctl.conf
- name: net.core.somaxconn=65535
  sysctl:
    name: net.core.somaxconn
    value: 65535
    state: present

- name: net.ipv4.ip_local_port_range=10240 63999
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: 10240  63999
    state: present

- name: net.ipv4.tcp_tw_recycle=0
  sysctl:
    name: net.ipv4.tcp_tw_recycle
    value: 0
    state: present

- name: net.ipv4.tcp_tw_reuse=1
  sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: 1
    state: present

- name: net.ipv4.tcp_max_syn_backlog=65535
  sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: 65535
    state: present

- name: net.ipv4.tcp_max_tw_buckets=1440000
  sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: 1440000
    state: present

- name: net.ipv4.tcp_window_scaling=1
  sysctl:
    name: net.ipv4.tcp_window_scaling
    value: 1
    state: present

- name: net.ipv4.tcp_congestion_control=htcp
  sysctl:
    name: net.ipv4.tcp_congestion_control
    value: htcp
    state: present

- name: net.core.netdev_max_backlog=250000
  sysctl:
    name: net.core.netdev_max_backlog
    value: 250000
    state: present

- name: net.ipv4.tcp_mtu_probing=1
  sysctl:
    name: net.ipv4.tcp_mtu_probing
    value: 1
    state: present

- name: net.ipv4.tcp_slow_start_after_idle=0
  sysctl:
    name: net.ipv4.tcp_slow_start_after_idle
    value: 0
    state: present

- name: fs.file-max=6511048
  sysctl:
    name: fs.file-max
    value: 6511048
    state: present

- name: net.netfilter.nf_conntrack_max=262144
  sysctl:
    name: net.netfilter.nf_conntrack_max
    value: 262144
    state: present

- name: net.ipv4.tcp_max_syn_backlog=4096
  sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: 4096
    state: present
    reload: yes
